### ISSUE TITLE
not working from 0.92

### ISSUE THREAD

**Issue by daboshman** [dimagoltsman/ha-custom-lovelace-cards#5]
i get an error because the send package is now changed.

**Comment by lpt2007** [comment]
same error here

**Comment by alex-0103** [comment]
Hello there, here is a quick and dirty fix:
change your ui-lovelace.yaml to
![grafik](https://user-images.githubusercontent.com/47693826/57318319-56afaf80-70fa-11e9-9e44-31c90fbec806.png)
that is, delete the broadlink_entity entry and add a host entry.


in content-card-remote-control.js change the call to hass.callService in _bindButtons like this
![grafik](https://user-images.githubusercontent.com/47693826/57318197-0afd0600-70fa-11e9-83a5-a41d446087d7.png)

This works for me. Maybe someone else finds this helpful.
Cheers
Alex

**Comment by guyyar89** [comment]
> Hello there, here is a quick and dirty fix:
> change your ui-lovelace.yaml to
> ![grafik](https://user-images.githubusercontent.com/47693826/57318319-56afaf80-70fa-11e9-9e44-31c90fbec806.png)
> that is, delete the broadlink_entity entry and add a host entry.
> 
> in content-card-remote-control.js change the call to hass.callService in _bindButtons like this
> ![grafik](https://user-images.githubusercontent.com/47693826/57318197-0afd0600-70fa-11e9-83a5-a41d446087d7.png)
> 
> This works for me. Maybe someone else finds this helpful.
> Cheers
> Alex

thanks alex but you can share the full code after your changes?
i mean ui-lovelace.yaml file and  content-card-remote-control.js file

**Comment by dimagoltsman** [comment]
fixed.
please update JS file, remove broadlink_entity from the settings and add broadlink_host with your broadlink ip
